services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db
networks:
  app-network:
    driver: bridge
