services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
